INSERT INTO jobs (JobID, Role, Employees, Location, JobType, WorkMode, Skills, Logo, CompanyName, CompanyLocation, Stipend, AboutCompany, AboutJobInternship, AdditionalInformation, Duration, userId) 
VALUES 
(1, 'Software Engineer', '20-50', 'New York', 'Full-Time', 'Office', 'JavaScript, React, Node.js', NULL, 'TechCorp', 'New York', 80000, 
'TechCorp is a leading software company specializing in web development and AI-driven solutions. With over a decade of industry experience, we aim to build innovative and scalable software products that empower businesses worldwide. Our team consists of skilled developers, designers, and engineers dedicated to delivering high-quality solutions to clients across multiple industries.', 
'As a Software Engineer at TechCorp, you will be responsible for developing, testing, and deploying scalable web applications. You will collaborate with cross-functional teams to design new features, optimize system performance, and ensure high code quality. We value strong problem-solving skills, teamwork, and a passion for technology. This role requires proficiency in JavaScript frameworks, backend APIs, and cloud-based architectures. You will have the opportunity to work on innovative projects and contribute to the company''s growth. The ideal candidate will have experience with modern front-end and back-end development, version control, and agile methodologies. Our work culture encourages continuous learning and knowledge sharing. You will work alongside talented engineers and get exposure to cutting-edge technologies in a dynamic environment.', 
'Candidates should have at least 2 years of experience in software development, with a strong grasp of React.js, Node.js, and database management. Experience with cloud platforms like AWS or Azure is a plus. Strong analytical skills and the ability to work in a fast-paced environment are essential. We offer competitive salaries, career growth opportunities, and a collaborative work culture.', 
'Permanent', 1),

(2, 'Data Analyst', '11-50', 'San Francisco', 'Internship', 'Hybrid', 'SQL, Python, Tableau', NULL, 'DataInsights', 'San Francisco', 2000, 
'DataInsights is a data-driven company that helps organizations make informed decisions using advanced analytics and machine learning. Our mission is to extract meaningful insights from data, enabling businesses to improve efficiency, customer satisfaction, and overall performance. Our team of data scientists and analysts work on complex projects that require deep analytical thinking and problem-solving skills.', 
'As a Data Analyst Intern, you will work with a team of experienced analysts to collect, clean, and analyze large datasets. You will generate reports and dashboards using tools like Tableau and Power BI, providing actionable insights to various departments. This role is an excellent opportunity for students or recent graduates looking to gain hands-on experience in data analytics and visualization. You will work on real-world business problems, handling structured and unstructured data to drive decision-making. We will provide mentorship and training to help you develop your skills and build a strong foundation in data analytics. Successful interns may receive an offer for a full-time position after completion.', 
'Candidates should be currently pursuing or have recently completed a degree in Data Science, Statistics, or a related field. Basic knowledge of SQL, Python, and data visualization tools is required. Strong analytical skills, attention to detail, and a passion for working with data are essential for success in this role.', 
'3 Months', 2), 

(3, 'Marketing Specialist', '20-50', 'Los Angeles', 'Contractual', 'Remote', 'SEO, Google Ads, Content Marketing', NULL, 'MarketPro', 'Los Angeles', 50000, 
'MarketPro is a digital marketing agency specializing in SEO, Google Ads, and content marketing. We work with brands across various industries to create high-performing marketing strategies that drive traffic, engagement, and conversions. Our team consists of creative professionals, strategists, and data analysts committed to delivering outstanding marketing solutions to our clients.', 
'We are looking for a Marketing Specialist to join our remote team on a contractual basis. You will be responsible for planning and executing digital marketing campaigns, optimizing SEO strategies, and managing paid advertisements on Google and social media platforms. The ideal candidate should have experience in digital marketing, a creative mindset, and strong analytical skills. Your role will also include working with content teams, A/B testing campaigns, and analyzing market trends to improve engagement. You will collaborate with clients to understand their needs and develop effective marketing strategies. A strong understanding of conversion rate optimization and marketing analytics will be essential.', 
'The ideal candidate should have a minimum of 3 years of experience in digital marketing. Experience in SEO, PPC advertising, and social media marketing is highly desirable. Strong communication skills, creativity, and the ability to analyze campaign performance are key to succeeding in this role.', 
'6 Months', 1); 